[plugin]
repository = "https://github.com/TheRedheadedWitch/FashionReport.git"
commit = "b524adf065ab15d12424be50d0c39e744f97b3dc"
owners = ["TheRedheadedWitch"]
project_path = "FashionReport"
changelog = "Updated project"
